### ISSUE TITLE
Issue: Not able to login.

### ISSUE THREAD

**Issue by SpeckyYT** [dcrime/Discord-Livebot-Upgrade#1]
Like the title says, I'm not able to login with a bot account.
When I enter the token, I hold for 1 second the enter key, then the "Token" box becomes red and nothing else happens.
I checked multiple tokens, but none work.

I hope you are able to help me in any way.

Here's the final result when trying to log in:
![image](https://user-images.githubusercontent.com/40666126/71924761-f349b600-318f-11ea-9a2f-c06a237923a6.png)

**Comment by SebOuellette** [comment]
Try using the original [Livebot](https://github.com/SebOuellette/Discord-LiveBot), which is further developed than this copy.

**Comment by SpeckyYT** [comment]
ok, I'll do that
